#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProyectoAndroid.Resource", IsApplication=true)]

namespace ProyectoAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int producto_categorias = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050014
			public const int BtnCancelar = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int BtnGuardar = 2131034133;
			
			// aapt resource value: 0x7f05000f
			public const int LblAccion = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int SpinnerCategoria = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int TxtCantidadInicial = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int TxtNombre = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int btnAddUser = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int btnAgregar = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int btnAgregarProducto = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int btnSignIn = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int btnSingUp = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int linearLayout1 = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int lvwProductos = 2131034126;
			
			// aapt resource value: 0x7f050008
			public const int rdbKilo = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int rdbPieza = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int rdgUnidad = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int spinnerCategoria = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int txtCantidad = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int txtComprobarPassword = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int txtNombre = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int txtPassword = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int txtUser = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AddUser = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CreateProduct = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Menu = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int MovimientosProductos = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
